"""initial pr schema

Revision ID: 01421d8dfaeb
Revises:
Create Date: 2026-01-15 06:27:12.107753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01421d8dfaeb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_table(
        "user_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=False),
        sa.Column("open_date", sa.DateTime(), nullable=False),
        sa.Column("submitter", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("last_update_date", sa.DateTime(), nullable=False),
        sa.Column("state", sa.Enum("OPEN", "MERGED", "CLOSED", name="prstate"), nullable=False),
        sa.Column("files_changed", sa.Integer(), nullable=False),
        sa.Column("lines_added", sa.Integer(), nullable=False),
        sa.Column("lines_deleted", sa.Integer(), nullable=False),
        sa.Column("commits_count", sa.Integer(), nullable=False),
        sa.Column("github_labels", sa.JSON(), nullable=False),
        sa.Column("filenames", sa.JSON(), nullable=False),
        sa.Column("commits_breakdown", sa.JSON(), nullable=False),
        sa.Column("reviewers", sa.JSON(), nullable=False),
        sa.Column("assignees", sa.JSON(), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("classify_tags", sa.String(length=500), nullable=True),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.Column("merged_by", sa.String(length=100), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "number", name="uq_repo_pr_number"),
    )
    op.create_table(
        "pr_user_tags",
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.Column("user_tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_tag_id"], ["user_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pr_id", "user_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pr_user_tags")
    op.drop_table("pull_requests")
    op.drop_table("user_tags")
    op.drop_table("repositories")
    # ### end Alembic commands ###
